### ISSUE TITLE
Bug: group firewall gid. 

### ISSUE THREAD

**Issue by eatwithforks** [cloudpassage/don-bot#22]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/app/runner.py", line 175, in slack_out_manager
    dec_msg = base64.decodestring(message[1])
  File "/usr/lib/python2.7/base64.py", line 328, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding

**Comment by eatwithforks** [comment]
1. with group that has no fw policy.
2. group id with quotes
3. group id with foobar

**Comment by eatwithforks** [comment]
uncheck smart quotes on mac.
not a problem w/ linux/windows.
